config/routes.rb
Rails.application.routes.draw do
  post "google_session", to: "google_session#session"
  root "dashboard#index"
  post '/create_patient', to: "dashboard#create_patient"
  post '/create_doctor', to: "dashboard#create_doctor"
  post '/create_appointment', to: "dashboard#create_appointment"
  
  
  
  
  get '/login', to: "session#index"
  post '/auth', to: "session#create"
  get '/logout', to: "session#logout"
  post '/fb_login', to: "session#fb_login"


  
  resources :users
  get "dashboard/index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/appointment.rb
class Appointment
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps

  field :disease, type: String

  belongs_to :doctor, class_name: "Doctor"
  belongs_to :patient, class_name: "Patient"
  belongs_to :user
end

app/models/doctor.rb
class Doctor
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  field :doctor_name, type: String
  field :phone, type: String
  field :specialisation, type: String

  has_many :appointments
  belongs_to :user
end

app/models/patient.rb
class Patient
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  include Mongoid::Timestamps
  field :patient_name, type: String
  field :phone, type: String

  has_many :appointments
  belongs_to :user
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  field :name, type: String
  field :email, type: String
  field :google_token, type: String
  field :facebook_token, type: String
  has_many :patients
  has_many :doctors
  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
 add_flash_types :danger, :info, :warning, :success

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url if current_user.nil?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authorize
    def index
        @user = current_user
        @patient = Patient.new
        @doctor = Doctor.new
        @appointment = Appointment.new
        @doctor_data = Doctor.all.pluck(:doctor_name, :id)
        @patient_data = Patient.all.pluck(:patient_name, :id)
        @appointment_data = Appointment.all
    end
    
    def create_patient
        puts patient_params
        @patient = current_user.patients.new(patient_params)
        puts @patient.inspect
        if @patient.save
            redirect_to root_path, notice: "Patient is created"
        else
            redirect_to root_path, notice: "Patient is  not created"
        end
    end

    def create_doctor
        @doctor = current_user.doctors.new(doctor_params)
        puts @doctor.inspect
        if @doctor.save
            redirect_to root_path, notice: "doctor is created"
        else
            redirect_to root_path, notice: "doctor is  not created"
        end
    end

    def create_appointment
        @appointment = current_user.appointments.new(appointment_params)
        puts @appointment.inspect
        if @appointment.save
            redirect_to root_path, notice: "appointment is created"
        else
            redirect_to root_path, notice: "appointment is  not created"
        end
    end

    private
    def patient_params
        params.require(:patient).permit(:patient_name, :phone)
    end
    def doctor_params
        params.require(:doctor).permit(:doctor_name, :phone, :specialisation)
    end
    def appointment_params
        params.require(:appointment).permit(:doctor_id, :patient_id, :disease)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

    def index

    end
    def create
        
        puts params[:session]
        
        user_data = params[:session]
        @user = User.find_by(email: user_data[:email])
        puts "out"
        if @user.present?
            puts "in"
            if @user.google_token == user_data[:google_token]
            puts "in2"
                session[:user_id] = @user.id
                cookies[:token] = @user.google_token
            redirect_to root_path, notice: "Thank you for SignUp"
            else
            redirect_to login_path
            end
        else
            @new_user =  User.new
            @new_user.name = user_data[:name]
            @new_user.email = user_data[:email]
            @new_user.google_token = user_data[:google_token]
            if @new_user.save
                session[:user_id] = @new_user.id
                cookies[:token] = @new_user.google_token
            redirect_to root_path, notice: "Thank you for SignUp"
            else
            redirect_to login_path
            end
        end
    end

    def fb_login
        puts params[:session]

        user_data = params[:session]
        @user = User.find_by(facebook_token: user_data[:facebook_token])
        if @user.present?
            session[:user_id] = @user.id
            cookies[:token] = @user.facebook_token
            redirect_to root_path, notice: "Thank you for SignUp" 
        else
            @new_user = User.new
            @new_user.name = user_data[:name]
            @new_user.facebook_token = user_data[:facebook_token]
            if @new_user.save
                session[:user_id] = @new_user.id
                cookies[:token] = @new_user.facebook_token
            redirect_to root_path, notice: "Thank you for SignUp"
            else
            redirect_to login_path
            end
        end
    end

    def logout
        session[:user_id] = nil
        cookies[:token] = nil
        redirect_to login_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/google_session_helper.rb
module GoogleSessionHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/index.html.erb
<div class="row">
    <script src="https://apis.google.com/js/platform.js" async defer></script>
    <meta name="google-signin-client_id" content="367164179713-o2vp44qfh28frcoe8mla19tm5lo7p9iq.apps.googleusercontent.com">
    <div class="col-md-12 col-sm-12 col-xs-12" ></div>
        <div class="col-md-4 col-sm-4 col-xs-4">
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
        </div>
        <div class="col-md-4 col-sm-4 col-xs-4">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12" >
                    <div class="col-md-6 col-sm-6 col-xs-6" style=" ">
                       <%= @user.name %>
                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-6"  style=" ">
                        <div class="g-signin2 hidden" data-onsuccess="onSignIn"></div>
                        <% if @user.google_token.present?%>
                            <a href="http://localhost:3000/logout" onclick="signOut();">Sign out</a>
                            <script>
                            function onSignIn(googleUser) {
                                var profile = googleUser.getBasicProfile();
                                var g_id  = profile.getId(); 
                                var str =  profile.getName();
                                console.log('Image URL: ' + profile.getImageUrl());
                                var email =   profile.getEmail();
                            }
                            </script>
                        <% elsif @user.facebook_token.present?%>
                            <a href="/logout" onclick="FB.logout();">Sign out</a> 
                        <% end %>
                        <script>
                            function signOut() {
                                var auth2 = gapi.auth2.getAuthInstance();
                                auth2.signOut().then(function () {
                                console.log('User signed out.');
                                });
                            }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 cl-sm-12 col-xs-12" style="margin-top:10px" >
        <div class="col-md-6 col-sm-6 col-xs-6 container_dash" style="padding-bottom: 127px; margin-left: -8px;">
            <div class="patient">
               <div class="col-md-1 col-sm-1 col-xs-1">
               </div>
               <div class="col-md-10 col-sm-10 col-xs-10">
                   
                   <div class="headPtaient dash_title">
                       <div class="title">
                           <h2 class="titleName" style="font-size: 18px;">Patient</h2>
                       </div>
                   </div>
                   <div class="patient_content">
                       <div class="patient_form">
                           <%= form_for @patient, url: create_patient_path do |f| %>
                           <fieldset>
                               <div class="patient_name_field">
                                   <%= f.text_field :patient_name, class:"dash_board_form", placeholder: "Patient Name" %>
                               </div>
                               <div class="patient_phone_number">
                                   <%= f.text_field :phone, class:"dash_board_form",placeholder:"Phone Number", required: true, onkeypress:'validate(event)', minlength:"10", maxlength:"10" %>
                                   <%#= f.hidden_field :user_id, value:%>
                               </div>
                               <div class="patient_submit" style="text-align: center;">
                                   <%= f.submit "Create Patient", class:"submit_button" %>
                               </div>
                           </fieldset>
                           <% end %>
                       </div>
                   </div>
               </div>
               <div class="col-md-1 col-sm-1 col-xs-1">
               </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 container_dash" style="margin-left: 8px;">
            <div class="doctor">
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
                <div class="col-md-10 col-sm-10 col-xs-10">
                    <div class="headDoctor dash_title">
                        <div class="title">
                            <h2 class="titleName" style="font-size: 18px;">Doctor</h2>
                        </div>
                    </div>
                    <div class="doctor_content">
                        <div class="doctor_form">
                            <%= form_for @doctor, url: create_doctor_path do |f| %>
                            <fieldset>
                                <div class="doctor_name_field">
                                    <%= f.text_field :doctor_name, class:"dash_board_form", placeholder:"Doctor Name" %>
                                </div>
                                <div class="doctor_phone_number">
                                    <%= f.text_field :phone, class:"dash_board_form",  placeholder:"Phone Number", required: true, onkeypress:'validate(event)', minlength:"10", maxlength:"10" %>
                                </div>
                                <div class="doctor_specialisation">
                                    <%= f.text_field :specialisation, class: "dash_board_form", placeholder:"Specialisation"%>
                                </div>
                                <div class="doctor_submit" style="text-align: center;">
                                    <%= f.submit "Create doctor", class:"submit_button" %>
                                </div>
                            </fieldset>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12 cl-sm-12 col-xs-12"  style="margin-top: 7px;"  >
        <div class="col-md-6 col-sm-6 col-xs-6 container_dash" style="padding-bottom: 120px; margin-left: -8px;">
            <div class="appointment">
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
                <div class="col-md-10 col-sm-10 col-xs-10">
                    <div class="headappointment dash_title">
                        <div class="title">
                            <h2 class="titleName" style="font-size: 18px;" > Appointment</h2>
                        </div>
                    </div>
                    <div class="appointment_content">
                        <div class="appointment_form">
                            <%= form_for @appointment, url: create_appointment_path do |f| %>
                            <fieldset>
                                <div class="appointment_name_field">
                                    <%=select_tag "appointment[doctor_id]", options_for_select(@doctor_data),{:prompt => "Select Doctor",:class => 'form-control dash_board_form',:style => 'border: 1px solid;'} %>
                                </div>
                                <div class="appointment_phone_number">
                                    <%=select_tag "appointment[patient_id]", options_for_select(@patient_data),{:prompt => "Select Patient",:class => 'form-control dash_board_form', :style => 'border: 1px solid;'} %>
                                </div>
                                <div class="appointment_specialisation">
                                    <%= f.text_field :disease, class: "dash_board_form", placeholder:"Disease"%>
                                </div>
                                <div class="appointment_submit" style="text-align: center;">
                                    <%= f.submit "Create appointment", class:"submit_button" %>
                                </div>
                            </fieldset>
                            <% end %>
                        </div>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-6 container_dash" style="margin-left: 8px;">
            <div class="table_main">
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
                <div class="col-sm-10 col-sm-10 col-xs-10">
                    <div class="table_header">
                        <div class="table_title">
                            <h3>View appointment</h3>
                        </div>
                    <div>
                    <div class="table_content">
                        <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                            <thead>
                                <tr>
                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 175px;">Patient name</th>
                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 175px;">Doctor Name</th>
                                    <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Name: activate to sort column descending" style="width: 175px;">Disease</th>
                                </tr>
                            </thead>
                            <tbody>
                                <%if @appointment_data.present? %>
                                    <% @appointment_data.each do |ap|%>
                                        <tr>
                                            <td><%= Patient.find_by(id: ap.patient_id).patient_name%></td>
                                            <td><%= Doctor.find_by(id: ap.doctor_id).doctor_name%></td>
                                            <td><%= ap.disease%></td>
                                        </tr>
                                    <% end %>
                                <% end %>    
                            </tbody>    
                        </table>
                    </div>
                </div>
                <div class="col-md-1 col-sm-1 col-xs-1">
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    function validate(evt) {
    var theEvent = evt || window.event;
    var key = theEvent.keyCode || theEvent.which;
    key = String.fromCharCode( key );
    var regex = /[0-9]|\./;
    if( !regex.test(key) ) {
      theEvent.returnValue = false;
      if(theEvent.preventDefault) theEvent.preventDefault();
    }
  }
</script>
<script>

function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response["authResponse"]["userID"]);
    console.log(response)
    console.log("Hello")
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    
    if (response.status === 'connected') {
        // Logged into your app and Facebook.
        testAPI();
    } else {
        // The person is not logged into your app or we are unable to tell.
        document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    }
    }

    function checkLoginState() {
    FB.getLoginStatus(function(response) {
        statusChangeCallback(response);
    });
        FB.logout(function(response) {
    // Person is now logged out
    });
    }


    window.fbAsyncInit = function() {
    FB.init({
        appId      : '409176242889594',
        cookie     : true,
        xfbml      : true,
        version    : 'v3.0'
    });
        
    FB.AppEvents.logPageView(); 
        
        
    };

    (function(d, s, id){
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) {return;}
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    function testAPI() {
            console.log('Welcome!  Fetching your information.... ');
            FB.api('/me', function(response) {
                console.log(response)
        var data = {
        name: response.name,
        facebook_token: response.id
        }
        var settings = {
        "async": true,
        "crossDomain": true,
        "url": "http://localhost:3000/fb_login",
        "method": "POST",
        "headers": {
            "content-type": "application/json",
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        "processData": false,
        "data": JSON.stringify(data)
        }

        $.ajax(settings).done(function (response) {
        window.location.replace("http://localhost:3000")
        });

        
        
        });
    }
       
       
       
       
</script>
<script>
    $('#datatable').DataTable({"order": []});
    
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpdDemoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 	  <%= yield %>
  </body>
</html>

app/views/session/index.html.erb
<div class="row">
<style>
._4z_b{
    height: 37px !important;
    width: 100px !important;
    padding-left: 20px !important;
}
.uiGrid ._51mz{
  height:37px !important;
}
</style>
<meta name="google-signin-client_id" content="367164179713-o2vp44qfh28frcoe8mla19tm5lo7p9iq.apps.googleusercontent.com">
<script src="https://apis.google.com/js/platform.js" async defer></script>
    <div class="col-md-12 col-sm-12 col-xs-12" style="text-align: center; margin-top: 85px;"><h2>Welcome to Demo app</h2></div>
    <div class="col-md-4 col-sm-4 col-xs-4">
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4" style="margin-top: 160px;border: 1px solid #4444;padding: 50px;border-radius: 11px;">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <div class="g-signin2" data-onsuccess="onSignIn"></div>
      </div>  
      <a class="hidden" href="#" onclick="signOut();">Sign out</a>
      <script>
          function signOut() {
            var auth2 = gapi.auth2.getAuthInstance();
            auth2.signOut().then(function () {
            console.log('User signed out.');
            });
          }
      </script>
      <div class="col-md-6 col-sm-6 col-xs-6" style="text-align: center;">
        <fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
        </fb:login-button>
        <div id="status"></div> 
      </div>  
    </div>
    <div class="col-md-4 col-sm-4 col-xs-4">
    </div>
</div>

<script>
 $(function(){ // jQuery dom ready event
    if (window.location.href.toLowerCase().indexOf("loaded") < 0) {
        window.location = window.location.href + '?loaded=1'
    }
});
function onSignIn(googleUser) {
  var profile = googleUser.getBasicProfile();
  console.log('ID: ' + profile.getId()); // Do not send to your backend! Use an ID token instead.
  console.log('Name: ' + profile.getName());
  console.log('Image URL: ' + profile.getImageUrl());
  console.log('Email: ' + profile.getEmail()); // This is null if the 'email' scope is not present.
  var data = {
      name: profile.getName(),
      google_token: profile.getId(),
      email: profile.getEmail()
  }
  var settings = {
  "async": true,
  "crossDomain": true,
  "url": "http://localhost:3000/auth",
  "method": "POST",
  "headers": {
    "content-type": "application/json",
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  },
  "processData": false,
  "data": JSON.stringify(data)
}

$.ajax(settings).done(function (response) {
  window.location.replace("http://localhost:3000")
});
}
</script>

<script>

 function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response["authResponse"]["userID"]);
    console.log(response)
    console.log("Hello")
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else {
      // The person is not logged into your app or we are unable to tell.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    }
  }

  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
        FB.logout(function(response) {
   // Person is now logged out
    });
  }


  window.fbAsyncInit = function() {
    FB.init({
      appId      : '409176242889594',
      cookie     : true,
      xfbml      : true,
      version    : 'v3.0'
    });
      
    FB.AppEvents.logPageView(); 
      
      
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));

    function testAPI() {
            console.log('Welcome!  Fetching your information.... ');
            FB.api('/me', function(response) {
                console.log(response)
        var data = {
        name: response.name,
        facebook_token: response.id
        }
        var settings = {
        "async": true,
        "crossDomain": true,
        "url": "http://localhost:3000/fb_login",
        "method": "POST",
        "headers": {
            "content-type": "application/json",
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        "processData": false,
        "data": JSON.stringify(data)
        }

        $.ajax(settings).done(function (response) {
        window.location.replace("http://localhost:3000")
        });

       
        
        });
    }




</script>